<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
	$descLength = $this->product_description_max_length;
?>

<div class="block block-basic category-products">
	<?php if ($this->title){ ?>
	<div class="block-title"><strong><?php echo $this->title ?></strong></div>
	<?php } ?>
    
    <?php 
	if(!$_productCollection->count()){ ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php  }else{
		$row = 0;
        $col= 0;
        $count = 1;
		$i=0; 
		$_collectionSize = $_productCollection->count();
		
		foreach($_productCollection as $_product){
			$i++;
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
		?>			            				
            
				<div class="product-wrap<?php if($i==1){ echo ' first'; }?>">
				
						<div class="item">
									
							<div class="product-image">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth,$imgHeight); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							</div>										
							
							<div class="product-content">
								<div class="product-name">
									<a class="fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
									<?php echo $_product->getName(); ?>
									</a>
								</div>						
								
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="clr"></div>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>	
							</div>
								
						</div>
					
					
				</div>
		<?php  }}	?>
	
</div>
