<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php if ($this->canShowBlock()): ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
    <div id="layered-navigation">
    <?php endif; ?>
        <div class="block block-layered-nav">
            <div class="block-title">
                <strong><span><?php echo $this->__('Shop By') ?></span></strong>
            </div>
            <?php echo $this->getStateHtml() ?>
            
            <div class="block-content">
                
                <?php if ($this->canShowOptions()): ?>
                    <?php /*<p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>*/ ?>
                    <dl id="narrow-by-list">
                        <?php $_filters = $this->getFilters() ?>
                        <?php foreach ($_filters as $_filter): ?>
                            <?php if ($_filter->getItemsCount()): ?>
                                <?php if(strtolower($_filter->getName())=="price"){?> 
                                <div class="wrap-price">
                                    <div class="inner">
                                        <div class="line"></div>                           
                                        <dt id="item-price">
                                        <?php echo $this->__($_filter->getName()); ?></dt>
                                        <dd><?php echo $_filter->getHtml() ?></dd>
                                    </div>
                                </div>
                            <?php
                            }else if(strtolower($_filter->getName())=="category"){?>
                                <div class="wrap-category">
                                    <dt><?php echo $this->__($_filter->getName()); ?></dt>
                                    <dd><?php echo $_filter->getHtml() ?></dd>
                                </div>
                            <?php }else{?>

                            <dt><?php echo $this->__($_filter->getName()); ?></dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>

                            <?php }?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                <?php endif; ?>               
            </div>
        </div>
    <?php if (!$this->getRequest()->isAjax()): ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
