<?php
/*------------------------------------------------------------------------
 # SM Slider - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$options = $this->getConfigObject();
$uniqued ='container_slider_'.rand().time();
$smarthelper= Mage::helper('slider/utils');
$list = $this->getProducts();
if(!empty($list)){?>
<div class="block-most-view wrap-upsell_pro">  
	<div id="upsell_pro" class="container-slider products-grid block"> 
	<?php echo $this->getScriptTags();?>


	<div id="<?php echo $uniqued; ?>" class="container-slider" style="<?php if( $options->anchor == "bottom" ){ echo "margin-bottom:40px;"; }?>">
			<div class="block-title"><?php echo $options->slider_title_text;?></div>
			<?php if(!empty($options->pretext)) { ?>
				<div class="pre-text"><?php echo $options->pretext; ?></div>
			<?php } ?>
			<?php if($options->anchor =="top"){?>
			<?php if($options->button_display == 1){?>
			<div class="page-button <?php echo $options->anchor;?> <?php echo $options->control;?>">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
			<?php }}?>
	
		<div class="slider not-js cols-6 <?php echo $options->deviceclass_sfx; ?>">
			<div class="vpo-wrap">
				<div class="vp">
					<div class="vpi-wrap">
					<?php foreach($list as $item){
							$_product = Mage::getModel('catalog/product')->load($item['id']);
							 $now = date("Y-m-d H:m:s");
					        $newsFrom= $_product->getNewsFromDate();
					        $newsTo=  $_product->getNewsToDate();
					        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
					        $special_from_date = $_product->getSpecialFromDate();
					        $special_to_date = $_product->getSpecialToDate();					       
						?>
						<div class="item">
							<div class="item-tmp"></div>

                            <div class="item-inner">   
                                    <div class="item-image">
                                    	 <!--SHOW 2 IMAGE FOR PRODUCTS-->
						                    <?php $_media = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages() ?>
						                    
						                    <?php $count_item=0; $check_img=0;?>
						                    
						                    <?php $check_img = count($_media);?>
                                        <a class="product-image" href="<?php echo $item['link'];?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> >
										<?php if( $options->product_source == "catalog" ){?>
											<img class="first_image" src="<?php echo $item['image'] ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 

						                    <?php if ($check_img >= 2): ?>
						                        <?php 
						                        $flag=0;
						                        foreach($_media as $_img): ?>
						                                <?php $count_item++;?>
						                                <?php if ($_img->getFile() == $_product->getSmallImage()){
						                                    if($count_item==$check_img){
						                                        $flag = 0;
						                                    }else{
						                                        $flag = 1;
						                                    }
						                                    continue;
						                                }  ?>
						                                <?php if($flag==1) { ?>
						                                <img class="last_image" src="<?php echo $item['image'] ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
						                                <?php  break; }?>
						                        <?php endforeach; ?>
						                        <?php 
						                            if($flag==0){
						                                foreach($_media as $_img){ ?>
						                                 <img class="last_image" src="<?php echo $item['image']; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
						                            <?php break; }
						                            }
						                        ?>
						                    <?php endif?>
						                    <?php }?>
										</a>
										 <?php                          
						                    if($newsFrom != ''){                            
						                    if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
						                        <div class='new-item'></div>
						                    <?php }
						                    }else{
						                    if(($newsTo != "") && $newsTo >= $now){ 
						                    ?>
						                        <div class='new-item'></div>
						                    <?php }
						                    }
						                    if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
						                        <div class='sale-item'>
						                            <span>
						                            <?php
						                            //$saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
						                            <?php   //print_r(floor($saleof)); ?>
						                            </span>
						                        </div>
						                <?php }
						                ?>  
                                    </div>                        
                                    
                                   
                            </div>
							<div class="item-info">
								<div class="info1">
									<h2 class="product-name">
										<a href="<?php echo $item['link']; ?>">
												<?php echo $_product->getName();?>
											</a>
									</h2>

									<?php 
									if( (int)$options->product_price_disp ){ 
										echo $this->getPriceHtml($_product, true);
									} ?> 
									<div class="w-temp2">
                                    <?php if($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    
                                    <?php 
                                    if($options->product_reviews_count == 1){
                                    	echo $this->getReviewsSummaryHtml($_product,'short') ;
                                	}
                                    ?>
                                    
                                    </div>
								</div>
													
							</div>
						</div>
					<?php }?>
					</div>
				</div>
			</div>
		</div>
		
		<?php if($options->anchor !="top"){?>
			<?php if($options->button_display == 1){?>
			<div class="page-button <?php echo $options->anchor;?> <?php echo $options->control;?>">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
		<?php }}?>
		
	</div>
	<?php if(!empty($options->posttext)) {  ?>
		<div class="post-text"><?php echo $options->posttext; ?></div>
	<?php } ?>
<?php }else {echo $this->__('Has no item to show!');}?>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($){
        $('#<?php echo $uniqued;?> .slider').responsiver({
            interval: 0 <?php //echo $options->delay;?>,
            speed: <?php echo $options->duration;?>,
            start: <?php echo $options->start -1;?>,
            step: <?php echo $options->scroll;?>,
            circular: true,
            preload: true,
			fx: 'slide',
            pause: 'hover',
            control:{
				prev: '#<?php echo $uniqued;?> .control-button li[class="preview"]',
				next: '#<?php echo $uniqued;?> .control-button li[class="next"]'
            },
			getColumns: function(element){
				var match = $(element).attr('class').match(/cols-(\d+)/);
				if (match[1]){
					var column = parseInt(match[1]);
				} else {
					var column = 1;
				}
				if (!column) column = 1;
				return column;
			}          
        });
    });
//]]>
</script>
</div>
</div>


