<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme; 
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) { ?>
<div id="cpanel_wrapper" style="direction: ltr">
	<div class="cpanel-head">
		<span>Template Settings</span>
		<div class="action cpanel-reset">
			<a class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>
	
	<div class="accordion" id="ytcpanel_accordion">
		<!--Theme-->
        <div class="accordion-group cpanel-theme cpanel-theme-color">
            <div class="accordion-heading">
                <a class="accordion-toggle"  data-parent="#ytcpanel_accordion" href="#ytitem_1">
					Theme Color
				</a>
            </div>
        	<div id="ytitem_1" class="accordion-theme">
                <div class="accordion-inner clearfix">
					<div class="color-theme">					
						
						<span title="Default" class="theme-color default<?php echo ($var_yttheme->getParam('sitestyle')=='default')?' active':'';?>">Default</span>
						<span title="Cyan" class="theme-color cyan<?php echo ($var_yttheme->getParam('sitestyle')=='cyan')?' active':'';?>">Cyan</span>
						<span title="Green" class="theme-color green<?php echo ($var_yttheme->getParam('sitestyle')=='green')?' active':'';?>">Green</span>
						<span title="Grey" class="theme-color grey<?php echo ($var_yttheme->getParam('sitestyle')=='grey')?' active':'';?>">Grey</span>

					</div>
				</div>
			</div>
        </div>
	
		<!--Store-->
		<div class="accordion-group cpanel-store">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_2">Layout Style</a>
			</div>
			<div id="ytitem_2" class="accordion-store">
				<div class="accordion-inner clearfix">
					<div class="cp-item">
						<div class="inner">
							<?php echo $this->getChildHtml('store_switcher');?>
						</div>
					</div>
					
					<div class="cp-item layout-option">
						<!--<span>Layout Style</span>-->
						<div class="inner">
							<span id="app_layoutstyle"></span>
							<select id="layoutstyle" onchange="javascript: onCPApply();" name="ytcpanel_layoutstyle" class="cp_select">
								<option value="1" <?php echo ($var_yttheme->getParam('layoutstyle') == '1')?' selected="selected"':'';?>>Full Width</option>
								<option value="2" <?php echo ($var_yttheme->getParam('layoutstyle') == '2')?' selected="selected"':'';?>>Boxed</option>
							</select>		
						</div>	
					</div>
					
					<script>
						 $jsmart(document).ready(function($){
						  // bind change event to select
						  $('#dynamic_select').bind('change', function () {
							  var url = $(this).val(); // get selected value
							  if (url) { // require a URL
								  window.location = url; // redirect
							  }
							  return false;
						  });
						});
					</script>
										
				</div>
			</div>
		</div>	
		
		
		<!-- Menu -->
		<div class="accordion-group cpanel-menu">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_6">
				Menu style </a>
			</div>
			<div id="ytitem_6" class="accordion-body">
				<div class="accordion-inner clearfix">
					<!-- Styles -->
					<div class="cp-item footer-background-color">
						<!--span>Styles</span-->
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
								<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
								<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="cpanel_btn" class="normal">
		<i class="icon-hand-left"></i>
	</div>
</div>

<script type="text/javascript">
	// <![CDATA[
    $jsmart(document).ready(function($){       
		function templateSetting(array){
			if(array['0']){
				$('.body-background-color input.miniColors').attr('value', array['0']);
				$('.body-background-color a.miniColors-trigger').css('background-color', array['0']);
				$('input.ytcpanel_bgcolor').attr('value', array['0']);
			}
			if(array['1']){
				$('.link-color input.miniColors').attr('value', array['1']);
				$('.link-color a.miniColors-trigger').css('background-color', array['1']);
				$('input.ytcpanel_linkcolor').attr('value', array['1']);
			}
			if(array['2']){
				$('.text-color input.miniColors').attr('value', array['2']);
				$('.text-color a.miniColors-trigger').css('background-color', array['2']);
				$('input.ytcpanel_textcolor').attr('value', array['2']);
			}
			if(array['3']){
				$('.header-background-color input.miniColors').attr('value', array['3']);
				$('.header-background-color a.miniColors-trigger').css('background-color', array['3']);
				$('input.ytcpanel_header-bgcolor').attr('value', array['3']);
			}
		}
		
		var array 			= Array('bgcolor','linkcolor','textcolor');

		var array_default 	= Array('#FFFFFF','#686868');
		var array_green 	= Array('#FFFFFF','#686868');
		var array_grey		= Array('#FFFFFF','#686868');
		var array_cyan   	= Array('#FFFFFF','#686868');
		
		$('.theme-color.default').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_default);
			onCPApply();
		});
		$('.theme-color.cyan').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_cyan);
			onCPApply();
		});
		$('.theme-color.green').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_green);
			onCPApply();
		});

		$('.theme-color.grey').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_grey);
			onCPApply();
		});
		
    });
	// ]]>
    </script>
<?php } ?>